### ISSUE TITLE
Invalid tarball when using provider

### ISSUE THREAD

**Issue by maray** [Chivo-SJ/Chivo-Data-Provider#3]
When downloading for example:
http://provider.chivo.cl/confirm?mous=A001_X122_X226

the dialog says "the file is 20 MB", but the file downloaded is only 8.8 MB. 

The downloaded file is a corrupted tarball:

```
mac:Downloads mauricio$ tar xzvf A001_X122_X226.tar.gz 
x calibrated.ms.image.c18o.mosaic.flux.fits: gzip decompression failed
tar: Error exit delayed from previous errors.
```

Maybe this is only happening in mac OS X, I haven't tried in Linux/Windows.

I attach the corrupted tarball 
[A001_X122_X226.tar.gz](https://github.com/ChileanVirtualObservatory/Chivo-Data-Provider/files/1287791/A001_X122_X226.tar.gz)

**Comment by camilo-nunez** [comment]
The problem is solved with MODCOD:001. Now the provider download the FITS file.
